services:
  nats:
    image: nats
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - ./storage/jetstream:/data

  nats-nui:
    image: ghcr.io/nats-nui/nui
    ports:
      - "31311:31311"
    volumes:
      - ./storage/nats-nui:/db

  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug

