apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiter
  labels:
    app: waiter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: waiter
  template:
    metadata:
      labels:
        app: waiter
    spec:
      containers:
      - name: waiter
        image: coffeeshop/waiter:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
